### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by dwillis** [TheUpshot/Bedfellows#2]
I thought about using the name Affinity, but there's a PyPy library with that name (albeit from 2006). I'd like to keep that basic idea, though, and short. Thoughts?

**Comment by dwillis** [comment]
Was looking at synonyms for affinity: simpatico? partiality?

**Comment by nikeiubel** [comment]
Would likeness be too awkward a word? I was looking at synonyms too and I'd
say that's the one that better captures the idea we're trying to convey.

If we want to go down a more creative route, we could go for "alliance
scores" or "symbiosis scores"? Or maybe "coalition scores" to make a play
on words?
Though these may not convey the idea as well as affinity.

That's a tough question, I'll keep thinking about it!
- Nikolas

**Comment by parisminton** [comment]
Cahoots?
