### ISSUE TITLE
No similar recipient committees for some cmtes

### ISSUE THREAD

**Issue by dwillis** [TheUpshot/Bedfellows#3]
This one, for instance: C00492785

**Comment by nikeiubel** [comment]
Thanks for catching this! This was nothing more than a dumb indentation
error introduced when I added code to handle error case. It's already
fixed. The results are:

Top 10 recipients most similar to C00492785 TED CRUZ FOR SENATE along with
cosine similarity scores are:

C00369033 TEXANS FOR SENATOR JOHN CORNYN INC 0.423940463896

C00437913 OLSON FOR CONGRESS COMMITTEE 0.416467968454

C00311043 BRADY FOR CONGRESS 0.399710248337

C00436386 FRIENDS OF JOHN BARRASSO 0.387311610162

C00472241 BILL FLORES FOR CONGRESS 0.384173232152

C00394957 SCALISE FOR CONGRESS 0.382545525441

C00392688 MCCAUL FOR CONGRESS INC 0.380663138925

C00303305 PETE SESSIONS FOR CONGRESS 2004 0.379426554622

C00197160 TEXANS FOR LAMAR SMITH 0.371655869867

C00540302 TIM SCOTT FOR SENATE 0.3715213416

C00393348 KENNY MARCHANT FOR CONGRESS 0.366307578536
